name: OpenMapTiles-Fetch-Data
on:
  workflow_dispatch:
    inputs:
      file_URL:
        description: 'input http://download.openstreetmap.fr/extracts/asia/china/anhui.osm.pbf osm file URL'
        required: true
        default: 'http://download.openstreetmap.fr/extracts/asia/china/anhui.osm.pbf'  
env:
  TZ: Asia/Shanghai

jobs:
  OpenMapTiles-Fetch-Data:
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2
      - name: Initialization running environment
        run: |
          sudo ln -sf /bin/bash /bin/sh 
          sudo mkdir -p /OpenMapTiles && sudo -E chmod 777 /OpenMapTiles
          sudo mkdir -p /UpReleaseArtifact && sudo -E chmod 777 /UpReleaseArtifact
          sudo mkdir -p /OpenMapTiles/myscripts && sudo -E chmod 777 /OpenMapTiles/myscripts
          cp scripts/*.sh /OpenMapTiles/myscripts
          chmod +x /OpenMapTiles/myscripts/*.sh
          /OpenMapTiles/myscripts/extern-disk-space.sh
      - name: Start OpenMapTiles 
        run: |
          cd /OpenMapTiles
          git clone https://github.com/EzEmbedded/openmaptiles.git -b master
          cd openmaptiles
          make
          make start-db
          make import-data
          curl -o data/custom.osm.pbf '${{ github.event.inputs.file_URL }}'
          # curl -o data/custom.osm.pbf http://download.openstreetmap.fr/extracts/asia/china/anhui.osm.pbf
          # make download area=new-york-latest   
          make import-osm
          make import-wikidata
          make import-sql
          du -h data/*
          docker ps
          # docker-compose exec -T postgres pg_dump -U openmaptiles openmaptiles --no-owner | gzip -9  > openmaptilesdb-dump.sql.gz
          # tar  cvzf - openmaptilesdb-dump.sql.gz | split -b 2040m - db-dump.tar.gz.
          # mv db-dump.tar.gz.* /UpReleaseArtifact
          make generate-bbox-file
          make generate-tiles-pg
          du -h data/*
          tar  cvzf - data/tiles.mbtiles | split -b 2040m - tiles-mbtiles.tar.gz.
          mv tiles-mbtiles.tar.gz.* /UpReleaseArtifact
          ls -al /UpReleaseArtifact
      - name: clear src release    #v1.0.0 is src
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: v1.0.0   #v1.0.0 is src
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: release src    #v1.0.0 is src
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/UpReleaseArtifact/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag:  "v1.0.0"    #v1.0.0 is src
