name: OpenMapTiles-Fetch-Data
on:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai

jobs:
  OpenMapTiles-Fetch-Data:
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2
      - name: Initialization running environment
        run: |
          sudo ln -sf /bin/bash /bin/sh 
          sudo mkdir -p /OpenMapTiles && sudo -E chmod 777 /OpenMapTiles
          sudo mkdir -p /OpenMapTiles/data && sudo -E chmod 777 /OpenMapTiles/data
          sudo mkdir -p /UpReleaseArtifact && sudo -E chmod 777 /UpReleaseArtifact
          sudo mkdir -p /OpenMapTiles/myscripts && sudo -E chmod 777 /OpenMapTiles/myscripts
          sudo mkdir -p /OpenMapTiles/mypatch && sudo -E chmod 777 /OpenMapTiles/mypatch
          cp scripts/*.sh /OpenMapTiles/myscripts
          cp patch/*.patch /OpenMapTiles/mypatch
          chmod 777 /OpenMapTiles/mypatch/*.patch
          chmod +x /OpenMapTiles/myscripts/*.sh
          /OpenMapTiles/myscripts/extern-disk-space.sh
      - name: fetch pack pakage src 
        run: |
          cd /OpenMapTiles
          git clone https://github.com/EzEmbedded/openmaptiles.git -b master
          cd openmaptiles
          make
          make start-db
          make import-data
          make download area=china   
          make import-osm
          make import-wikidata
          make import-sql
          du -h data/*
          docker ps
          docker-compose exec -T postgres pg_dump -U openmaptiles openmaptiles --no-owner | gzip -9  > ./data/openmaptilesdb-dump.sql.gz
          tar  cvzf - data/ | split -b 2040m - db-data.tar.gz.
          mv db-data.tar.gz.* /UpReleaseArtifact
          # make generate-tiles-pg
          ls -al /UpReleaseArtifact
      - name: clear src release    #v1.0.0 is src
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: v1.0.0   #v1.0.0 is src
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: release src    #v1.0.0 is src
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/UpReleaseArtifact/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag:  "v1.0.0"    #v1.0.0 is src
